#include QMK_KEYBOARD_H
#include "mymacros.h"
#include "tapdances.h"
#include "myunicode.h"
#include "mycombos.h"

#define X(n) UM(n)
#define XP(n,m) UP(n,m)

/* * Keymap */
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
/* ** Colemak-DH */
[0] = LAYOUT_split_3x6_3(KC_TAB,
                         KC_Q,
                         KC_W,
                         KC_F,
                         KC_P,
                         KC_B,
                         KC_J,
                         KC_L,
                         KC_U,
                         KC_Y,
                         LT(5, KC_SCLN), // WM and misc
                         KC_ESC,

                         KC_ENT,
                         KC_A,
                         KC_R,
                         KC_S,
                         KC_T,
                         LGUI_T(KC_G),
                         KC_M,
                         KC_N,
                         KC_E,
                         KC_I,
                         LT(4, KC_O), // VIM
                         LGUI_T(KC_QUOT),

                         KC_DEL,
                         LALT_T(KC_Z),
                         KC_X,
                         KC_C,
                         KC_D,
                         LT(4, KC_V), // VIM
                         LT(7, KC_K), // Unicode
                         KC_H,
                         KC_COMM,
                         KC_DOT,
                         RGUI_T(KC_SLSH),
                         LALT_T(KC_MINS),

                         KC_BSPC,
                         OSL(1), // Numbers and Symbols
                         KC_SPC,
                         OSM(MOD_LSFT),
                         OSM(MOD_LCTL),
                         OSL(2) // FN and misc
                           ),

/* ** Numbers and Symbols */
  [1] = LAYOUT_split_3x6_3(KC_TRNS,
                           KC_EXLM,
                           KC_AT,
                           KC_HASH,
                           KC_DLR,
                           KC_PERC,
                           KC_CIRC,
                           KC_AMPR,
                           KC_ASTR,
                           KC_BSLS,
                           TD(EQL_EQLCOL), /* KC_EQL, */
                           KC_TRNS,

                           KC_ENT,
                           KC_1,
                           KC_2,
                           KC_3,
                           KC_4,
                           KC_5,
                           KC_6,
                           KC_7,
                           KC_8,
                           KC_9,
                           KC_0,
                           KC_DOT,

                           LT(3, KC_DEL), //RESET
                           KC_UNDS,
                           KC_LCBR,
                           KC_LBRC,
                           TD(LPRN_ARROW), /* KC_LPRN, */
                           KC_PLUS,
                           KC_PIPE,
                           TD(RPRN_ARROW), /* KC_RPRN, */
                           KC_RBRC,
                           KC_RCBR,
                           KC_TILD,
                           KC_GRV,

                           KC_TRNS,
                           KC_TRNS,
                           KC_TRNS,
                           KC_TRNS,
                           KC_TRNS,
                           KC_TRNS
                           ),
/* ** Fn and Misc */
  [2] = LAYOUT_split_3x6_3(KC_PSCR,
                           KC_F1,
                           KC_F2,
                           KC_F3,
                           KC_F10,
                           MS_BTN3,
                           KC_HOME,
                           KC_PGDN,
                           KC_PGUP,
                           KC_END,
                           TD(VOLU_3X),
                           KC_ESC,

                           KC_TRNS,
                           TD(F4_EMACSCLIENT),
                           KC_F5,
                           KC_F6,
                           MS_BTN1,
                           MS_BTN2,
                           KC_LEFT,
                           KC_DOWN,
                           KC_UP,
                           KC_RGHT,
                           MS_WHLD,
                           MS_WHLU,

                           TD(MENU_TERM), /* KC_APP, */
                           TD(F7_RUN1),
                           TD(F8_RUN2),
                           TD(F9_XKILL),
                           KC_F11,
                           KC_F12,
                           MS_LEFT,
                           MS_DOWN,
                           MS_UP,
                           MS_RGHT,
                           TD(VOLD_3X),
                           MO(3), //RESET

                           KC_TRNS,
                           KC_LCTL,
                           /* LSFT_T(send_string(".  ")), */
                           TD(SFT_END_SENT), /* KC_LSFT, */
                           KC_TRNS,
                           KC_TRNS,
                           KC_TRNS
                           ),
/* ** RESET */
  [3] = LAYOUT_split_3x6_3(QK_BOOT,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           XMODMAPRESET,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           QK_BOOT,

                           KC_CAPS,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_MRWD,
                           KC_NO,
                           KC_NO,
                           KC_MFFD,
                           KC_NO,
                           KC_NO,

                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_TRNS,

                           KC_TRNS,
                           KC_TRNS,
                           KC_TRNS,
                           KC_TRNS,
                           KC_TRNS,
                           KC_TRNS
                           ),

/* ** Vim */
  [4] = LAYOUT_split_3x6_3(TD(VIMSPLIT_H_DEL_OTHER),
                           TD(VIMSPLIT_V_DEL_OTHER_V),
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           VIMDOW_L,
                           VIMDOW_D,
                           VIMDOW_U,
                           VIMDOW_R,
                           KC_NO,
                           KC_NO,

                           EMACS_WIND_C,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           LGUI(KC_H),
                           LGUI(KC_J),
                           LGUI(KC_K),
                           LGUI(KC_L),
                           KC_NO,
                           TD(VIM_SR_SR_ALL),

                           KC_NO,
                           EMACS_FRAME_P,
                           EMACS_FRAME_N,
                           VIMBUF_P,
                           VIMBUF_N,
                           KC_NO,
                           TD(VIMSIZE_H_CC_ROT),
                           TD(VIMSIZE_J_FLIP),
                           TD(VIMSIZE_K_FLOP),
                           TD(VIMSIZE_L_C_ROT),
                           KC_NO,
                           KC_NO,

                           KC_TRNS,
                           KC_TRNS,
                           KC_TRNS, /* LGUI_T(KC_SPC), */
                           KC_TRNS,
                           KC_TRNS,
                           MO(6) // VIM 2
                           ),

/* ** WM and Misc */
  [5] = LAYOUT_split_3x6_3(WM_TILE_TL,
                           WM_TILE_T,
                           WM_TILE_TR,
                           WM_MV_WSPC_P,
                           WM_MV_WSPC_N,
                           WM_MAX,
                           WM_SWAP_0,
                           WM_SWAP_1,
                           WM_SWAP_2,
                           WM_SWAP_3,
                           KC_NO, // ;
                           KC_NO,

                           WM_TILE_L,
                           RGUI_TAB,
                           WM_TILE_R,
                           WM_WSPC_P,
                           WM_WSPC_N,
                           WM_TILE_C,
                           WM_EXTEND_0,
                           WM_EXTEND_1,
                           WM_EXTEND_2,
                           WM_EXTEND_3,
                           WM_EXTEND_4,
                           KC_NO,

                           WM_TILE_BL,
                           WM_TILE_B,
                           WM_TILE_BR,
                           RGUI_TAB_QUICK,
                           RGUI_TAB_R_QUICK,
                           WM_MIN,
                           WM_SCALE_0,
                           WM_SCALE_1,
                           WM_SCALE_2,
                           WM_SCALE_3,
                           KC_NO,
                           KC_NO,

                           WM_FILL_V,
                           WM_FILL_H,
                           WM_UNDO,
                           WM_REDO,
                           MO(8), //WM Grid
                           MO(8)  //WM Grid
                           ),
/* ** VIM 2 */
  [6] = LAYOUT_split_3x6_3(KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           EMACS_GIT_HUNK_N,
                           EMACS_GIT_HUNK_P,
                           KC_NO,
                           KC_NO,
                           KC_NO,

                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,

                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,

                           EMACS_HEADING_P,
                           EMACS_HEADING_N,
                           KC_TRNS,
                           KC_TRNS,
                           KC_TRNS,
                           KC_TRNS
                           ),

/* ** Unicode and Dynamic Macros*/
  [7] = LAYOUT_split_3x6_3(ORG_QUOTE_BLOCK,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           XP(UUMLAUT,UUMLAUTC),
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,

                           ORG_SRC_BLOCK,
                           XP(AUMLAUT,AUMLAUTC),
                           KC_NO,
                           X(ESZETT),
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           X(AIGU),
                           KC_NO,
                           XP(OUMLAUT,OUMLAUTC),
                           KC_NO,

                           TD(GRASP_CAP_NOTE),
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           MO(9), //V //emoji
                           KC_NO, //K
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,
                           KC_NO,

                           /* QK_DYNAMIC_MACRO_RECORD_START_2, */
                           /* QK_DYNAMIC_MACRO_PLAY_2, */
                           /* QK_DYNAMIC_MACRO_RECORD_STOP, */
                           KC_TRNS,
                           KC_TRNS,
                           KC_TRNS,
                           KC_TRNS,
                           KC_TRNS,
                           /* QK_DYNAMIC_MACRO_PLAY_1, */
                           /* QK_DYNAMIC_MACRO_RECORD_START_1 */
                           KC_TRNS
                           ),

/* ** WM grid */
  [8] = LAYOUT_split_3x6_3(WM_TILE_31_1,
                            WM_TILE_32_11,
                            WM_TILE_32_22,
                            WM_TILE_33_11,
                            WM_TILE_33_21,
                            WM_TILE_33_31,
                            WM_AUTOTILE_AUTO,
                            WM_AUTOTILE_21,
                            WM_AUTOTILE_31,
                            KC_NO,
                            KC_NO, // ;
                            KC_NO,

                            WM_TILE_31_2,
                            WM_TILE_32_12,
                            WM_TILE_32_31,
                            WM_TILE_33_12,
                            WM_TILE_33_22,
                            WM_TILE_33_32,
                            WM_AUTOTILE_12,
                            WM_AUTOTILE_22,
                            WM_AUTOTILE_32,
                            KC_NO,
                            WM_MOVE_0,
                            KC_NO,

                            WM_TILE_31_3,
                            WM_TILE_32_21,
                            WM_TILE_32_32,
                            WM_TILE_33_13,
                            WM_TILE_33_23,
                            WM_TILE_33_33,
                            WM_AUTOTILE_13,
                            WM_AUTOTILE_23,
                            WM_AUTOTILE_33,
                            WM_MOVE_3,
                            WM_MOVE_2,
                            WM_MOVE_1,

                            RGUI_TAB_QUICK,
                            RGUI_TAB_R_QUICK,
                            KC_TRNS,
                            KC_TRNS,
                            KC_TRNS,
                            KC_TRNS
                            ),
/* ** Emoji*/
  [9] = LAYOUT_split_3x6_3(X(EMOJI00),
                            X(EMOJI01),
                            X(EMOJI02),
                            X(EMOJI03),
                            X(EMOJI04),
                            X(EMOJI05),
                            X(EMOJI06),
                            X(EMOJI07),
                            X(EMOJI08),
                            X(EMOJI09),
                            X(EMOJI10),
                            X(EMOJI11),

                            X(EMOJI12),
                            X(EMOJI13),
                            X(EMOJI14),
                            X(EMOJI15),
                            X(EMOJI16),
                            X(EMOJI17),
                            X(EMOJI18),
                            X(EMOJI19),
                            X(EMOJI20),
                            X(EMOJI21),
                            X(EMOJI22),
                            X(EMOJI23),

                            X(EMOJI24),
                            X(EMOJI25),
                            X(EMOJI26),
                            X(EMOJI27),
                            X(EMOJI28),
                            KC_NO,
                            KC_NO,
                            X(EMOJI29),
                            X(EMOJI30),
                            X(EMOJI31),
                            X(EMOJI32),
                            X(EMOJI33),

                            X(EMOJI34),
                            X(EMOJI35),
                            X(EMOJI36),
                            X(EMOJI37),
                            X(EMOJI38),
                            X(EMOJI39)
                            )
};
