##
# Project Title
#
# @file
# @version 0.1


# all: rules.mk
#     qmk compile -kb crkbd -km custom
#     qmk flash -kb crkbd -km custom

# .PHONY: all

# # end
crkbd: ; qmk compile -kb crkbd -km custom ; qmk flash -kb crkbd -km custom
